services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file: .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - url-shortener

  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - url-shortener

volumes:
  postgres_data:

networks:
  url-shortener:
    driver: bridge
